/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package database.insert;

import database.Access;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import logic.IUser;
import logic.datatype.CommentEvent;
import utility.Constant;
import utility.Pair;

/**
 *
 * @author xuan
 */
public class InsertCommentWork implements ICoreWork {

    CommentEvent _ac;

    public InsertCommentWork(CommentEvent ac) {
        this._ac = ac;
    }

    @Override
    public int dowork(Pair<Connection, Statement> pair) throws SQLException {
        Connection c = Access.getConnection();
        String[] autogeneratedKeys = new String[]{"id", "time"};
        PreparedStatement ps = c.prepareStatement(
                "INSERT INTO comment (userid, hostid, parentid, comment, type) VALUES (?, ?, ?, ?, ?)", autogeneratedKeys);
        ps.setInt(1, _ac.getUserid());
        ps.setLong(2, _ac.getHostid());
        ps.setLong(3, _ac.getParentCommentid());
        ps.setString(4, _ac.getComment());
        ps.setString(5, _ac.getType().name());
        pair.setKey(c);
        pair.setValue(ps);
        ps.executeUpdate();
        ResultSet rs = ps.getGeneratedKeys();
        if (rs.first()) {
            _ac.setCommentid(rs.getLong(1));
            _ac.setTime(new Date());
        }
        return Constant.DATABASE_MODIFY_SUCCESS;
    //    c.commit();
    }

}
